### ISSUE TITLE
Continous deployment/integration…

### ISSUE THREAD

**Issue by torjohannessen** [knowit/okr-tracker#10]
Continous deployment/integration…

**Comment by thomasdtran** [comment]
Oppsett av  continous deployment for både prod og dev

**Comment by KristianZE** [comment]
Ferdig med CD for dev. Jobber videre med dette etter vi har oppdatert prod.

**Comment by thomasdtran** [comment]
Pipeline for prod fungerer ikke som den skal, men man kan fortsatt ta i bruk "Deploy to PROD" ved å manuelt starte den.

**Comment by thomasdtran** [comment]
Ferdig med pipeline for prod
