### ISSUE TITLE
Oppsett av nye instanser

### ISSUE THREAD

**Issue by torjohannessen** [knowit/okr-tracker#11]
Strømlinjeforme oppsett av nye instanser, evt. vurdere om vi kan utvide så dette kan bli et produkt for flere virksomheter (eget organisasjonsnivå) (Sondre)
Muligens også tilrettelegge for Egen admin per org.

**Comment by SondreODahl** [comment]
Oppsett av nye instanser er foreløpig gjort med terraform, og andre oppgaver kan spesifiseres i nye issues. Markerer denne som lukket da hovedoppgaven er i mål.
