### ISSUE TITLE
Unable to add tidsperiode , mål , metrikker og nøkkelresultater for vårt nye team

### ISSUE THREAD

**Issue by MargreteIversen** [knowit/okr-tracker#21]
Hei,
Det er ikke mulig å legge til noen mål, nøkkelresultater eller metrikker  i OKR-trackeren. Mulig det er brukerfeil, men legger ved input.

**Comment by MargreteIversen** [comment]
![Image](https://user-images.githubusercontent.com/126468083/223448889-e4e2ca72-3ec4-46ec-b926-fdb9538f4790.png)

**Comment by KristianZE** [comment]
Tror dette har en sammenheng med issue #16

**Comment by KristianZE** [comment]
Tested this on dev, works for me. It is important that users have admin access (as a list, not boolean) though.

**Comment by MargreteIversen** [comment]
Hvordan løser vi best dette? Det burde være mulig for standard-roller å editere innad eget team?

**Comment by KristianZE** [comment]
Det er litt rart, for jeg ser ikke at Oslo-koden har møtt på dette problemet. En løsning ville vært å gjøre det slik at man kun trenger vanlig admin rettigheter (ikke superAdmin som er ett nivå over) for å legge til/gjøre endringer i team. Det skulle egentlig vært slik, slik jeg forstår det.

**Comment by KristianZE** [comment]
Det er mulig at firebase functions er problemet, ettersom det virker som man ikke har permission til å opprette med mindre man er superAdmin. Så kanskje det er en permission check i firebase functions som hindrer det.

**Comment by KristianZE** [comment]
Vi fant ut av det. Det var bare litt forvirring. Man må nå kun være medlem for å gjøre tidligere nevnte funksjoner, slik som ønsket. Flytter til done.
