### ISSUE TITLE
Utvikle en oversikt over antall brukere i OKR-trackere-

### ISSUE THREAD

**Issue by MargreteIversen** [knowit/okr-tracker#32]
Som en admin bruker ønsker jeg en oversikt over antall brukere som har vært logget inn siste 12 måneder. 

Ikke viktig å se detaljer på hvem, men at noen har logget inn (GDPR).

Knyttet til mål om å øke antall interne brukere 
https://okr.knowit.no/okr-tracker-core-team-Hx1rAzDEBqKammJxUiBV/

**Comment by MargreteIversen** [comment]
Det ligger antall brukere her: https://console.firebase.google.com/u/0/project/okr-tracker-knowit/authentication/users
Dog ev. om vi kan verifisere at dette faktisk stemmer? Har vi så mange som 160 brukere?

Gir dette menng @janhenrik ? Dvs. at vi har hatt 160 som har blitt koblet til en OKR tracker?

**Comment by KristianZE** [comment]
https://firebase.google.com/docs/auth/admin/manage-users 
Er en del kode her for bulk uthenting av brukere med firebase sin admin SDK.
